project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Bio
      - href: projects.qmd
        text: Projects
    right: 
      - icon: github
        menu:
          - text: Website Source Code
            url: https://github.com/taiglonergan/personal-website
  page-footer:
    right: "&copy; 2024, Taig Lonergan"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

  

execute:
  freeze: auto

